# Generated by Django 4.2.6 on 2023-12-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="documents/")),
                (
                    "modified_document",
                    models.FileField(
                        blank=True, null=True, upload_to="modified_documents/"
                    ),
                ),
            ],
        ),
    ]
