# Generated by Django 4.2.6 on 2024-01-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_listing_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist_mark",
            field=models.BooleanField(default=False),
        ),
    ]
