# Generated by Django 4.2.6 on 2024-01-15 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_listing_watchlist_mark"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "listing_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auctions.listing",
                    ),
                ),
            ],
            bases=("auctions.listing",),
        ),
        migrations.RemoveField(
            model_name="listing",
            name="watchlist_mark",
        ),
    ]
