# Generated by Django 4.2.6 on 2024-01-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_watchlist_remove_listing_watchlist_mark"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="url",
            field=models.CharField(default="/listing/1", max_length=1000),
            preserve_default=False,
        ),
    ]
