# Generated by Django 4.2.6 on 2024-02-01 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_listing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="item_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
