# Generated by Django 5.0.3 on 2024-06-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jjnofish", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadeddocument",
            name="fish_word",
        ),
        migrations.RemoveField(
            model_name="uploadeddocument",
            name="replacement_word",
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="word_pairs",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
