# Generated by Django 5.0.3 on 2024-05-02 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="post_id",
        ),
        migrations.AddField(
            model_name="post",
            name="id",
            field=models.AutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="post",
            name="liked_by",
        ),
        migrations.AddField(
            model_name="post",
            name="liked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="Post_liked_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
