# Generated by Django 5.0.3 on 2024-05-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_alter_post_liked_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="liked_by",
            field=models.CharField(blank=True, max_length=100000),
        ),
    ]
